steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: './news_crawler'
  args:
  - gcloud
  - functions
  - deploy
  - articles_recommender
  - --region=asia-southeast1
  - --source=./
  - --trigger-topic=crawl-news
  - --runtime=python39
  - --entry-point=recommend_articles_for_user
  
options:
  logging: CLOUD_LOGGING_ONLY